name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: joacoferroni/appointment-api:latest
      -
        name: Deploy to DO
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.USERNAME }}
          script: |
            echo "login to server success"
            docker rm (docker stop $(docker ps -a -q --filter="name=psicofer_api_c"))
            docker rmi joacoferroni/appointment-api:latest
            docker pull joacoferroni/appointment-api:latest
            docker run -d --network="host" --restart=unless-stopped --name="psicofer_api_c" joacoferroni/appointment-api:latest 
