name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Deploy to DO
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "login to server success"
            docker pull joacoferroni/appointment-api:latest
            docker run -d --network="host" --restart=unless-stopped --name="psicofer_api_c" joacoferroni/appointment-api:latest 
