name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: joacoferroni/appointment-api:latest
      -
        name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          script: |
            echo "login to server success"
      -
        name: Remove current container
        run: docker rm (docker stop $(docker ps -a -q --filter="name=psicofer_api_c"))
      -
        name: Remove current image
        run: docker rmi joacoferroni/appointment-api:latest
      -
        name: Pull latest image
        run: docker pull joacoferroni/appointment-api:latest
      -
        name: Run latest image
        run: docker run -d --network="host" --restart=unless-stopped --name="psicofer_api_c" joacoferroni/appointment-api:latest 
