name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Remove current container
        continue-on-error: true
        run: docker rm $(docker stop $(docker ps -a -q --filter="name=psicofer_api_c"))
      -
        name: Remove current image
        continue-on-error: true
        run: docker rmi joacoferroni/appointment-api:latest
      -
        name: Pull latest image
        run: docker pull joacoferroni/appointment-api:latest
      -
        name: Run latest image
        run: docker run -d --network="host" --restart=unless-stopped --name="psicofer_api_c" joacoferroni/appointment-api:latest 
